### ISSUE TITLE
My Issues with scheduLight

### ISSUE THREAD

**Issue by Heyam-A** [aau-zid/scheduLight#5]
Hello Martin Schrott,

Nice work for scheduLigh, I'm following your steps to configure my BBB meeting rooms. However, I couldn't find any config.yml file inside my BBB server, there's only  (/usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml) .. and I'm sure how to find the file you pointed to. 
How can I find it ?

It will be very useful if you provide a video on how scheduLight works, so people with low technical skills can follow. 

Have a nice day,
regards, 
Heyam

**Comment by mtsonline** [comment]
Hi @Heyam-A 
don't think of schedulight being something you integrate into bbb. See it as an external tool that controls bbb/greenlight.

that said, just follow the steps in the readme. checkout schedulight 
and open the directory.
in there all files you may need are located, including the config.yml. there is an example for the config yml you can use to create your actual config.yml.

there really is no magic a video could show you ;-)
hth

**Comment by Heyam-A** [comment]
Clear, Thank you!
